Traceback (most recent call last):
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\eval.py", line 13, in <module>
    from problems.online_contract_edgeAI import gpt
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\gpt.py", line 1, in <module>
    def agent_solver_v2(v: np.ndarray, content: list[dict]) -> np.ndarray:
NameError: name 'np' is not defined
