Traceback (most recent call last):
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\eval.py", line 13, in <module>
    from problems.online_contract_edgeAI import gpt
  File "E:\Coding\pythonProject\llm4contract\problems\online_contract_edgeAI\gpt.py", line 16
    bounds = [(0, 1)] for _ in range(n_outcomes)]
                                                ^
SyntaxError: unmatched ']'
